### ISSUE TITLE
I think that the website should always redirect to HTTPS

### ISSUE THREAD

**Issue by yassineim** [bcoin-org/bcoin-org.github.io#128]

**Comment by tynes** [comment]
We should host the bcoin docs under `hs.zone` as `bcoin.hs.zone` and use TLS there. Just need to buy the `bcoin` TLD on the Handshake testnet. Since it may not be up for auction yet, we may have to wait

**Comment by pinheadmz** [comment]
@chjj has the keys to the domain, we really need to make this change. Also we should add subdomains `browser.bcoin.io` and `api.bcoin.io` and expose more public services

**Comment by pinheadmz** [comment]
This has been fixed.
