### ISSUE TITLE
Guide to getting a full node running on VPS

### ISSUE THREAD

**Issue by bucko13** [bcoin-org/bcoin-org.github.io#35]
A guide for running on AWS and Digital Ocean similar to the OpenBazaar Guide: https://openbazaar.zendesk.com/hc/en-us/articles/207852873-Guide-to-Setting-up-OpenBazaar-Server-on-a-VPS

Should include: 
- Both VPS options
- At minimum a description of difference between doing SPV and Full Node, guide should be for full node though
- Description of resource requirements
- Guide should describe a secure setup
- Guide should include how to interact with your node via SSH

**Comment by Bucko13** [comment]
![bounty badge](https://api.bountysource.com/badge/issue?issue_id=50080957)

**Comment by gsora** [comment]
Should this guide target both AWS and DigitalOcean in a single take, or the bounty is for two separate articles?

**Comment by Bucko13** [comment]
It should target both. There shouldn't be too much differentiation between the two since the architecture are pretty similar.

**Comment by gsora** [comment]
I see on bountysource that someone is already working on a document. Is the bounty still open for other entries?

**Comment by Bucko13** [comment]
Yep! That work seems to have stalled so it's definitely still open for other entries.

**Comment by gsora** [comment]
Great! I'll fork the repo and start working on my guide as soon as
possible.

Il 27 nov 2017 00:33, "Buck Perley" <notifications@github.com> ha scritto:

**Comment by bucko13** [comment]
Resolved with PR #70

**Comment by bucko13** [comment]
@tenthirtyone make sure to claim the bounty on bountysource! 😄
