### ISSUE TITLE
Guide to wallet structure and creating wallets with bcoin

### ISSUE THREAD

**Issue by Bucko13** [bcoin-org/bcoin-org.github.io#38]
Should cover the following: 
- HD vs. non-HD wallets
- Key management
- Account management
- Mnemonic generation
- Tokens and API key management (see docs: http://bcoin.io/api-docs/index.html#reset-authentication-token)

**Comment by Bucko13** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=50080954)](https://www.bountysource.com/issues/50080954-guide-to-wallet-structure-and-creating-wallets-with-bcoin?utm_source=50080954&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by sangaman** [comment]
Quick question for clarification, regarding key management should that just focus on the KeyRing class and how you can use that to get info about your keys, or would that ideally cover broader topics like key storage techniques or concepts like public vs private keys, generating keys, etc? Although I suppose that latter part ties in to hd vs non hd wallets and account management anyway.

**Comment by sangaman** [comment]
Thanks, I added a bit more to the javascript examples section on working with keys directly.

**Comment by Bucko13** [comment]
Thanks for the guide! Looks great.
