### ISSUE TITLE
Wallet send tx default rate

### ISSUE THREAD

**Issue by julesGoullee** [bcoin-org/bcoin-org.github.io#41]
In [wallet doc](http://bcoin.io/api-docs/index.html#send-a-transaction) when it run in regtest this 100 fee is too few: tx create without error , but the state in always in unconfirmed status (after insertion in block without any arror), with 1000 fee no prob, it may create some confuse situation

**Comment by Bucko13** [comment]
Were you running this via the CLI? There is a PR currently up in the bcoin repo that would probably address this: https://github.com/bcoin-org/bcoin/pull/289

The rate is pretty variable depending on the network you're running on and in regtest it's pretty much irrelevant. The node will reject fees that are "absurdly high" as it says in the error message in the logs.

If this isn't what you're seeing or you're not doing this through the CLI could you tell me what error the node is giving you?

**Comment by julesGoullee** [comment]
Any error ! The node accept tx, the process mempool, add in block, save new block execute with no errors, the tx is in chain but balance or not updated, that work correctly with hight fees

**Comment by Bucko13** [comment]
Sorry I'm not really following. If there was a problem sending the transaction there should have been an error. I saw a similar error when testing it out myself, but you have to make sure you're looking at the node logs (usually in `~/.bcoin/[network_name]/debug.log`). Again, this might have to do with the units you are using and the logs will give you more information on this.
