### ISSUE TITLE
Guide for Timelocks in Bcoin

### ISSUE THREAD

**Issue by bucko13** [bcoin-org/bcoin-org.github.io#45]
A guide on implementing timelocked transactions in Bcoin. The guide should focus on building the scripts out from scratch, including an example with manual tx management and one using the walletdb/client.

Topics to include:

* What is nlocktime?
* Introduce the CheckLockTimeVerify and CheckSequenceVerify opcodes
* Use some real world use case to illustrate your example: e.g. Inheritance transaction to send money to your children, some business contract where funds are released after certain time, etc.
* Include other potential use cases for timelocks in Bitcoin transactions and also, as per the [ReadMe](https://github.com/bcoin-org/bcoin-org.github.io), ways your examples could be improved and built out for production
* Ideally would link to a repo with working version of the code

:link:https://www.bountysource.com/issues/50370461-guide-for-timelocks-in-bcoin?utm_source=50370461&utm_medium=shield&utm_campaign=ISSUE_BADGE ![Bountysource](https://api.bountysource.com/badge/issue?issue_id=50370461):link:

**Comment by EddieOne** [comment]
@Bucko13 Could you do this in the next week or so? I'm switching to Bcoin today and I swapped some [coin](https://blockchain.info/tx/e88a211b7e9710daf2c1c4ce21f789e231b94f1f2468947bcdceffbfd5c5b533) to bump the priority queue. Although this is a bit more limiting than my original plan, this guide would still be incredibly useful.

**Comment by Bucko13** [comment]
Hey Eddie, great to hear you’re shifting over to bcoin! Not sure we’ll be getting to it this week unfortunately. Focus is shifting onto other things for the time being as we just published a good slew of new ones the past couple weeks. You can try offering a bounty through the bountysource.com page and try and bump up the priority and offer some incentive to get someone from the community to put one together if you’d like it more urgently though! (Some instructions on that in the readme for this repo)

**Comment by EddieOne** [comment]
Hi Buck, Alright not a problem. It's something that can wait as it's documentation only. I got excited to continue my work and was hoping the bcoin team would make it easy. I will a try a bounty next time, as you're right, the community may want to step in.

**Comment by Bucko13** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=50370461)](https://www.bountysource.com/issues/50370461-guide-for-timelocks-in-bcoin?utm_source=50370461&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Bucko13** [comment]
We'll try and share it out to see if anyone is interested in taking a crack at it. Feel free to share it out on social media, etc. as well!

**Comment by EddieOne** [comment]
Ok, I will do the same. Thanks for adding the bounty!

**Comment by bucko13** [comment]
@EddieOne We finally have a guide up as a PR that solves this. Feel free to take a look at the draft and let me know if you have any feedback! https://github.com/bcoin-org/bcoin-org.github.io/pull/88

**Comment by bucko13** [comment]
Posted!
