### ISSUE TITLE
Litecoin Donation?

### ISSUE THREAD

**Issue by EddieOne** [bcoin-org/bcoin-org.github.io#47]
I'm impressed by all the work with Bcoin and would like to send a few usd worth of coin. Some wallets are struggling with BTC fees though. It seems fitting to send some litecoin since I'm interested in Lcoin for the moment. How about litecoin donations?

**Comment by Bucko13** [comment]
Glad you like the work! Unfortunately no place for litecoin donations (apparently the main Litecoin team are not big fans of alternative implementations either so it's not a major long term thing we're supporting), but you should be able to send via shapeshift :)

**Comment by EddieOne** [comment]
I guess some people don't like free money. 🙃 It's good to know where the support is at before investing too much time. I bet confirmation bias makes it hard to competing teams to support each other with a big picture outlook. It's probably just a matter of time, so I will wait and ask again later if given the chance.

**Comment by Bucko13** [comment]
To be honest it's more a matter of overhead. For one team to cover many different implementations, and even to be managing different wallets, can add a lot of overhead to have manage and isn't really sustainable long term unfortunately. Inter-team cooperation however is always welcome!
