### ISSUE TITLE
Cross-Origin error causes GitHub fork button to break

### ISSUE THREAD

**Issue by bucko13** [bcoin-org/bcoin-org.github.io#54]
Steps to Reproduce:
1. Go to guides
2. Click on `API Docs` link in `Checkout our API Docs or the Full Documentation`
3. Click back to go back to the guides
4. Fork is a text link instead of the button

It looks like a cross origin error is thrown only when navigating back as per the steps above. Error looks like:
```
buttons.js:1 Uncaught DOMException: Blocked a frame with origin "http://bcoin.io" from accessing a cross-origin frame.
    at https://buttons.github.io/buttons.js:1:66506
    at HTMLIFrameElement.l (https://buttons.github.io/buttons.js:1:796)
```
(credit to @inje for finding the bug)

**Comment by pinheadmz** [comment]
Can't reproduce -- close?

**Comment by bucko13** [comment]
Yep! Seems to have been resolved.
