### ISSUE TITLE
Multisig Wallet Guide

### ISSUE THREAD

**Issue by bucko13** [bcoin-org/bcoin-org.github.io#63]
There is already a guide for [multisig transactions](https://github.com/bcoin-org/bcoin-org.github.io/blob/staging/guides-markdown/multisig-tx.md) so this should focus instead on setting up multi-signature wallets. The following details/examples should be included:

* setting up normal "hot wallet" for live signing
* setting up a watch only wallet for a multisig wallet. This should include instructions on how to watch for transactions coming in to that wallet (e.g. getting the xpubkeys necessary, importing them, and setting up the watch/notification events)
* example use cases (e.g. situations where the extra security is useful, different numbers of signers and m-of-n situations, etc.) 
* Using the multisig across devices- this should include some walk-thru of the  actual process of passing the MTX around to the different wallets for signing.

**Comment by pinheadmz** [comment]
Closed by https://github.com/bcoin-org/bcoin-org.github.io/pull/162
